### PR TITLE
Included some tests and minor bug fixes.

### PR DESCRIPTION
**Pull request by jacob-hughes**
This PR should serve as a way to simply get travis integration into the project, so additional PRs will have to build before they can be submitted into the project.

### CODE REVIEW

**Comment by ltratt** [comment]
This feels like it should be (at least) two commits: one adding the travis file; and another one (or more) adding code and tests. Can we split it up?

**Comment by jacob-hughes** [comment]
Sure

**Comment by jacob-hughes** [comment]
Okay, broken that into some smaller commits

**Comment by ltratt** [comment]
OK, so when the tests have passed should I merge as-is?

**Comment by jacob-hughes** [comment]
Yes please! Then I will upload the next one ;)

**Comment by jacob-hughes** [comment]
Looks like all is well. Can we merge?

**Pull request merged**
